apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-active
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: bg-active.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: blue-green-active
            port:
              number: {{ .Values.port }}