apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: blue-green
  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
      - name: rollouts-demo
        image: {{ .Values.repo }}:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port }}
  strategy:
    blueGreen: 
      activeService: blue-green-active
      previewService: blue-green-preview
      autoPromotionEnabled: false