kind: Service
apiVersion: v1
metadata:
  name: {{ template "blue-green.name" .}}-preview
spec:
  selector:
    app: {{ template "blue-green.name" .}}
  ports:
  - protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}