kind: Service
apiVersion: v1
metadata:
  name: blue-green-preview
spec:
  selector:
    app: blue-green
  ports:
  - protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}