name: canary
port: 80
targetPort: 80

repoName: 4836297/blue-green-test
tag: canary-onee
replica: 2

ingress:
  path: /
  host: kreo-app.com

image:
  pullPolicy: IfNotPresent

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
