apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.repoName }}:{{ .Values.tag }}
          ports:
            - containerPort: 5000
          env:
          - name: POSTGRES_USER
            value: "username"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_DB
            value: "postgres"
          - name: POSTGRES_HOST
            value: "postgres.application.svc.cluster.local"
          - name: POSTGRES_PORT
            value: "5432"
          - name: DATABASE_URL
            value: "postgresql://username:password@postgres.application.svc.cluster.local:5432/postgres"
