kind: Service
apiVersion: v1
metadata:
  name: app-kreo-svc
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  ports:
  - protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}