apiVersion: apps/v1
kind: Deployment
metadata:
  name: kreo-app
  labels:
    app: kreo-app
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: kreo-app
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: kreo-app
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: kreo-app
          image: 4836297/maintenance:finish 