apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary
spec:
  replicas: 10
  minReadySeconds: 30
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: rollouts-demo
        image: {{ .Values.repoName }}:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port }}
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 1h # 1 hour
      - setWeight: 20
      - pause: {} # pause indefinitely